exclude: __pycache__|\.git|\.venv|\.vscode|build|dist|env|migrations|venv|\.secrets\.baseline$|sbom-cyclonedx.json|fonts|.*large.*|.*\.qcow2|.*\.vma
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.2
    hooks:
      - id: bandit
        args: ["-c", ".bandit.yaml"]
  - repo: https://github.com/psf/black
    rev: 25.12.0
    hooks:
      - id: black
  # - repo: https://github.com/ibm/detect-secrets
  #   rev: 0.13.1+ibm.64.dss
  #   hooks:
  #     - id: detect-secrets
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-jinja
  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--config", ".flake8"]
  - repo: https://github.com/tillig/json-sort-cli
    rev: v3.0.0
    hooks:
      - id: json-sort
        args:
          - --autofix
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
        args: ["--config=.markdownlint.yaml"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.5.5
    hooks:
      - id: forbid-crlf  # Forbid files containing CRLF end-lines to be committed
      - id: forbid-tabs  # Forbid files containing tabs to be committed
      - id: remove-crlf  # Replace CRLF end-lines by LF ones before committing
      - id: remove-tabs  # Replace tabs by whitespaces before committing
  - repo: https://github.com/PyCQA/pylint
    rev: v4.0.4
    hooks:
      - id: pylint
        args: ["--rcfile=.pylintrc"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-check  # Run the linter
        args: [--fix]
      - id: ruff-format  # Run the formatter
  - repo: https://github.com/google/yamlfmt
    rev: v0.20.0
    hooks:
      - id: yamlfmt
        args: [-conf, .yamlfmt]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: [--format, parsable, --strict, -c, .yamllint.yaml]
  - repo: local
    hooks:
      - id: cyclonedx-generate
        name: Generate CycloneDX SBOM
        entry: bash -c "cyclonedx-py poetry --with dev -o sbom-cyclonedx.json"
        language: system
  - repo: local
    hooks:
      - id: bomber-scan
        name: Scan SBOM
        entry: bash -c "bomber scan sbom-cyclonedx.json"
        language: system
        pass_filenames: false
